### ISSUE TITLE
Switch to new CodiMD repository

### ISSUE THREAD

**Issue by SISheogorath** [weseek/growi-docker-compose#28]
I just saw that you are still using the old repository.

CodiMD switch to an own organization with [a new repository](https://github.com/codimd/server). If you wonder why, have a look at [our Vision](https://github.com/codimd/server/issues/10).

We continue the community version there and I would also like to offer help to you. Is there something we can do to improve the integration between CodiMD and Growi?

Would love to hear your thoughts and feedback :)

**Comment by yuki-takei** [comment]
@SISheogorath 

Hi.
I glanced over codimd/server#10 and hackmdio/codimd#1170.
And congrats about forking. I am cheering for you.

## Current Status

As you say, growi-docker-compose references CodiMD 1.2.0 currently. 

We have been discussing in our team about simultaneously editing since last month. Now we are considering developing a new built-in editor that can edit simultaneously without CodiMD.

### Reasons

Although it's true that one of the reasons is the license of CodiMD changed to AGPLv3, the other reason is more important; we realized that we will not able to make truely confortable user experience with integrating with other system.

GROWI need an ES Module of CodeMirror that have two furtures.

1. It Integrate to ot.js
1. It is a loose coupling and GROWI can import it

So as long as CodiMD is provided as server software, it will be less important to GROWI in the future.  (expecially after develop a new built-in editor)


> Is there something we can do to improve the integration between CodiMD and Growi?

If CodiMD will provide the current editor parts as npm package, we should switch to use it. I think it will be awesome if it publish under MIT.


## As a fan

I think codimd/cli is useful and very exciting project. I hope CodiMD will grow as a fan.

**Comment by SISheogorath** [comment]
I see, hope to see more of you guys in future :)

CodiMD definitely lacks the developers to get the editor independent in a short term perspective. And even when we'll move it into an independent repository, it'll be AGPL licensed as we believe that this is the right license for our software.

Still happy to see you're moving forwards and I look towards a very interesting future with growi.

**Comment by yuki-takei** [comment]
GROWI dev team decided to implement the built-in editor with ot.js.
We will switch to the new CodiMD repos when it is time to do it.
